// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.
// Copyright Epic Games, Inc. All Rights Reserved.
#include "MetaXRAcousticMap.h"
#include "AudioDevice.h"
#include "Engine/StaticMesh.h"
#include "EngineUtils.h"
#include "HAL/PlatformFileManager.h"
#include "IMetaXRAudioPlugin.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "MetaXRAcousticGeometry.h"
#include "MetaXRAcousticMaterial.h"
#include "MetaXRAcousticProjectSettings.h"
#include "MetaXRAudioUtilities.h"
#ifdef META_NATIVE_UNREAL_PLUGIN
#include "MetaXRAudioContextManager.h"
#endif
#include "MetaXR_Audio.h"
#include "Misc/FileHelper.h"
#include "Runtime/Core/Public/Serialization/CustomVersion.h"

#include "Misc/EngineVersionComparison.h"
#if UE_VERSION_OLDER_THAN(5, 2, 0)
#include "MaterialShared.h"
#else
#include "Materials/MaterialRenderProxy.h"
#endif

#define WITH_EDITOR_GIZMOS (WITH_EDITOR && WITH_EDITORONLY_DATA)
#define UE_ACOUSTIC_MAP_FILE_EXTENSION ".xramap"

#if WITH_EDITOR
void UMetaXRAcousticMap::GenerateFileNameIfEmpty() {
  if (!FilePath.IsEmpty() || GetOwner() == nullptr) {
    return;
  }
  MetaXRAudioUtilities::CreateMetaXRAcousticContentDirectory(META_XR_AUDIO_DEFAULT_SAVE_FOLDER);
  FString LevelName = MetaXRAudioUtilities::GetActorLevelName(GetOwner());
  FString Suggestion = LevelName.IsEmpty() ? GetOwner()->GetActorNameOrLabel() : LevelName;
  FilePath = FPaths::Combine(META_XR_AUDIO_DEFAULT_SAVE_FOLDER, Suggestion + UE_ACOUSTIC_MAP_FILE_EXTENSION);
  UE_LOG(LogAudio, Display, TEXT("No file path specified, using the autogenerated name of: %s"), *FilePath);
}

void UMetaXRAcousticMap::CheckIfOnlyMapInLevel() {
  UWorld* World = GetWorld();
  if (World == nullptr) {
    return;
  }

  TArray<FString> LevelsWithMap;
  for (TActorIterator<AActor> ActorItr(World); ActorItr; ++ActorItr) {
    AActor* CurrentActor = *ActorItr;
    UMetaXRAcousticMap* MapComponent = CurrentActor->FindComponentByClass<UMetaXRAcousticMap>();
    if (MapComponent) {
      // Check that this actor does not have multiple acoustic maps attached to it
      TArray<UMetaXRAcousticMap*> MapComponents;
      CurrentActor->GetComponents<UMetaXRAcousticMap>(MapComponents);
      if (MapComponents.Num() > 1) {
        UE_LOG(
            LogAudio,
            Error,
            TEXT("There are %i maps on the actor %s, ensure there is only one Acoustic Map per level"),
            MapComponents.Num(),
            *CurrentActor->GetActorNameOrLabel());
      }

      // Check that there are no other actors within the level that have an acoustic map
      FString CurrentLevel = MetaXRAudioUtilities::GetActorLevelName(CurrentActor);
      if (LevelsWithMap.Contains(CurrentLevel)) {
        UE_LOG(
            LogAudio,
            Warning,
            TEXT("An Acoustic Map alreadys exists for the level %s, ensure there is only one Acoustic Map per level"),
            *CurrentLevel);
      } else {
        LevelsWithMap.Add(CurrentLevel);
      }
    }
  }
}

static uint32_t ReportComputeProgress(void* UserData, const char* String, float Progress) {
  UMetaXRAcousticMap* Context = (UMetaXRAcousticMap*)UserData;
  if (Context == nullptr) {
    UE_LOG(LogTemp, Error, TEXT("Can't cast user data to MetaXRAcousticMapComponent"));
    return false;
  }

  // Get the time since the start of the computation.
  uint64 ElapsedTime = Context->CheckTimer();

  // Reset the stage starting time if entering a new stage
  if (Context->GetDescription() != String) {
    Context->SetStageStartingTimeSeconds(ElapsedTime);
  }

  Context->SetDescription(String);
  Context->SetComputeProgress(Progress);
  Context->SetComputeTimeSeconds(ElapsedTime - Context->GetStageStartingTimeSeconds());

  return !Context->IsComputeCanceled();
}

void FAsyncSceneMappingTask::DoWork() {
  FString FilePath = AcousticMapComponent->GetFilePath();
  if (FilePath.IsEmpty()) {
    UE_LOG(LogAudio, Warning, TEXT("No file path set for acoustic map"));
    return;
  }

  AcousticMapComponent->Description = "";
  AcousticMapComponent->ComputeProgress = 0.0f;

  (void)OVRA_CALL(ovrAudio_InitializeAudioSceneIRParameters)(&Parameters);

  // UI is in centimeters but ovrAudio API is in meters
  float UnitScale = 0.01f;
  Parameters.minResolution = AcousticMapComponent->MinSpacing * UnitScale;
  Parameters.maxResolution = AcousticMapComponent->MaxSpacing * UnitScale;
  Parameters.headHeight = AcousticMapComponent->HeadHeight * UnitScale;
  Parameters.maxHeight = AcousticMapComponent->MaxHeight * UnitScale;
  const FVector ovrGravityVector = MetaXRAudioUtilities::ToOVRVector(AcousticMapComponent->GravityVector);
  Parameters.gravityVector[0] = (float)ovrGravityVector.X;
  Parameters.gravityVector[1] = (float)ovrGravityVector.Y;
  Parameters.gravityVector[2] = (float)ovrGravityVector.Z;
  Parameters.reflectionCount = AcousticMapComponent->ReflectionCount;
  Parameters.callbacks.userData = AcousticMapComponent;
  Parameters.callbacks.progress = ReportComputeProgress;
  Parameters.thisSize = sizeof(ovrAudioSceneIRParameters);

  uint32_t flags = 0;
  if (AcousticMapComponent->bStaticOnly)
    flags |= ovrAudioSceneIRFlag_StaticOnly;
  if (AcousticMapComponent->bNoFloating)
    flags |= ovrAudioSceneIRFlag_NoFloating;
  if (AcousticMapComponent->bDiffraction)
    flags |= ovrAudioSceneIRFlag_Diffraction;

  if (bMapOnly) {
    flags |= ovrAudioSceneIRFlag_MapOnly;
    AcousticMapComponent->bHasCustomPoints = false;
  }

  Parameters.flags = static_cast<ovrAudioSceneIRFlags>(flags);

  ovrResult ComputeResult;
  UE_LOG(LogAudio, Display, TEXT("Acoustic Map computation is now being launched on a separate thread"));
  if (AcousticMapComponent->bCustomPointsEnabled && !bMapOnly) {
    TArray<FVector3f> Points;
    Points.SetNumUninitialized(AcousticMapComponent->PointsOVR.Num());
    // Cached Points are stored in ovrAudio space without transform applied, so no conversions needed here
    for (int32 i = 0; i < AcousticMapComponent->PointsOVR.Num(); i++) {
      FVector PointD = AcousticMapComponent->PointsOVR[i];
      Points[i] = FVector3f(PointD.X, PointD.Y, PointD.Z);
    }
    ComputeResult =
        OVRA_CALL(ovrAudio_AudioSceneIRComputeCustomPoints)(Map, &Points[0].X, AcousticMapComponent->PointsOVR.Num(), &Parameters);
  } else {
    ComputeResult = OVRA_CALL(ovrAudio_AudioSceneIRCompute)(Map, &Parameters);
  }

  if (ComputeResult != ovrSuccess) {
    if (!AcousticMapComponent->bComputeCanceled) {
      AcousticMapComponent->bComputeFinished = true;
      UE_LOG(LogAudio, Warning, TEXT("Unable to compute acoustic map %p"), Map);
    } else {
      UE_LOG(LogAudio, Warning, TEXT("Computation for for acoustic map %p was cancelled by the user"), Map);
    }
    return;
  } else {
    UE_LOG(
        LogAudio,
        Display,
        TEXT("Acoustic Map computation has completed successfully for map %p after %f seconds"),
        Map,
        AcousticMapComponent->CheckTimer());
  }

  ovrAudioSceneIRStatus Status;
  (void)OVRA_CALL(ovrAudio_AudioSceneIRGetStatus)(Map, &Status);

  // Delete the old file first to ensure new result is fresh
  FString FullFilePath = FPaths::ProjectContentDir() / FilePath;
  IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
  if (PlatformFile.FileExists(*FullFilePath)) {
    UE_LOG(LogAudio, Warning, TEXT("Overwriting old acoustic map file at %s"), *FullFilePath);
    PlatformFile.DeleteFile(*FullFilePath);
  }
  MetaXRAudioUtilities::CreateMetaXRAcousticContentDirectory(FPaths::GetPath(FilePath));

  // Write the file
  ovrResult Result = OVRA_CALL(ovrAudio_AudioSceneIRWriteFile)(Map, TCHAR_TO_ANSI(*FullFilePath));
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to save acoustic map to file %s"), *FullFilePath);
  } else {
    UE_LOG(LogAudio, Display, TEXT("Successfully saved acoustic map to file %s"), *FullFilePath);
  }

  UE_LOG(LogAudio, Log, TEXT("Acoustic Map computation has status %i and writing to file has result %i"), Status, Result);

  AcousticMapComponent->UpdateCachedPoints();
}
#endif // if WITH_EDITOR

UMetaXRAcousticMap::UMetaXRAcousticMap() {
  bAutoActivate = true;
  PrimaryComponentTick.bCanEverTick = true;
  bWantsInitializeComponent = true;
  bTickInEditor = true;
#if WITH_EDITOR
  SetupSphereVertices();
#endif
}

UMetaXRAcousticMap::~UMetaXRAcousticMap() {}

void UMetaXRAcousticMap::StartInternal(bool AutoLoad) {
  // Ensure that the IR is not initialized twice.
  if (CachedMap != nullptr) {
    UE_LOG(LogAudio, Warning, TEXT("Already initialized, skipping init"));
    return;
  }

  CheckMapTransformValid();

  // Create the internal Acoustic Map.
#ifdef META_NATIVE_UNREAL_PLUGIN
  if (OVRA_CALL(ovrAudio_CreateAudioSceneIR)(FMetaXRAudioContextManager::GetContext(GetOwner(), GetWorld()), &CachedMap) != ovrSuccess) {
    UE_LOG(
        LogAudio,
        Warning,
        TEXT(
            "Unable to create Acoustic Map. Please check that the Spatialization Plugin and Reverb Plugin are set to Meta XR Audio in project settings. Restart the project after setting."));
#else
  if (OVRA_CALL(ovrAudio_CreateAudioSceneIR)(FMetaXRAudioLibraryManager::Get().GetPluginContext(), &CachedMap) != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to create Acoustic Map. Please check the Meta XR Audio binaries have been placed correctly."));
#endif
    return;
  } else {
    UE_LOG(LogAudio, Log, TEXT("Created Acoustic Map %p"), CachedMap);
  }

  // Load the serialized Acoustic Map.
  if (MetaXRAudioUtilities::PlayModeActive(GetWorld())) {
    LoadData();
  } else if (AutoLoad) {
    // Create the full file path
    if (FilePath.IsEmpty()) {
      UE_LOG(LogAudio, Warning, TEXT("No file path is specified for the Acoustic Map"));
      return;
    }
    FString FullFilePath = FPaths::ProjectContentDir() / FilePath;

    // Check if the file exists
    IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
    if (!PlatformFile.FileExists(*FullFilePath)) {
      UE_LOG(LogAudio, Warning, TEXT("The specified file does not exist: %s"), *FullFilePath);
      return;
    }

    // Do a blocking load from file when not playing so inspector can update immediately
    if (OVRA_CALL(ovrAudio_AudioSceneIRReadFile)(CachedMap, TCHAR_TO_ANSI(*FullFilePath)) != ovrSuccess) {
      UE_LOG(LogAudio, Warning, TEXT("Unable to create internal Acoustic Map"));
      return;
    } else {
#if WITH_EDITOR
      UpdateCachedPoints();
#endif
      UE_LOG(LogAudio, Log, TEXT("Successfully loaded Acoustic Map from file %s"), *FullFilePath);
    }
  }

  ApplyTransform();
}

void UMetaXRAcousticMap::DestroyInternal() {
#if WITH_EDITOR
  // Make sure to stop any compute jobs
  if (bComputing) {
    CancelCompute();
    FinishCompute();
  }
#endif

  if (CachedMap != nullptr) {
    // Destroy the Acoustic Map.
    UE_LOG(LogAudio, Log, TEXT("Destroying Acoustic Map %p"), CachedMap);
    if (OVRA_CALL(ovrAudio_DestroyAudioSceneIR)(CachedMap) != ovrSuccess) {
      UE_LOG(LogAudio, Warning, TEXT("Unable to destroy Acoustic Map"));
      return;
    }
    CachedMap = nullptr;
  }
}

void UMetaXRAcousticMap::LoadData() {
  if (FilePath.IsEmpty()) {
    UE_LOG(LogAudio, Warning, TEXT("No filepath for MetaXRAcousticMap"));
    return;
  }

  FString FullFilePath = FPaths::ProjectContentDir() / FilePath;
#if WITH_EDITOR
  if (!FPaths::FileExists(FullFilePath)) {
    UE_LOG(LogAudio, Warning, TEXT("Acoustic map file not found: %s"), *FullFilePath);
    return;
  }
#endif

  // Read the file data into a byte array
  TArray<uint8> FileData;
  if (!FFileHelper::LoadFileToArray(FileData, *FullFilePath)) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to load audio acoustic map file: %s"), *FullFilePath);
    return;
  }

  ovrResult Result;
  Result = OVRA_CALL(ovrAudio_AudioSceneIRReadMemory)(CachedMap, (const int8_t*)FileData.GetData(), FileData.Num());
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Unable to read audio acoustic map from memory: %s"), *FullFilePath);
    return;
  } else {
    UE_LOG(LogAudio, Log, TEXT("Loaded acoustic map from memory: %s to %p"), *FullFilePath, CachedMap);
  }

  // Now that the map is loaded ensure that it is enabled
  Result = OVRA_CALL(ovrAudio_AudioSceneIRSetEnabled)(CachedMap, true);
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to enable Acoustic Map %p"), CachedMap);
  } else {
    UE_LOG(LogAudio, Log, TEXT("Enabled Acoustic Map: %p"), CachedMap);
  }

  // Also ensure the transform is up to date
  ApplyTransform();
}

#if WITH_EDITOR
bool UMetaXRAcousticMap::Compute(bool bMapOnly, bool bBlockingCompute) {
  // Don't allow computing more than once at a time
  if (bComputing) {
    UE_LOG(LogAudio, Warning, TEXT("Cannot compute: computation in progress"));
    return false;
  }

  if (GetOwner() == nullptr) {
    return false;
  }

  if (MetaXRAudioUtilities::PlayModeActive(GetWorld())) {
    UE_LOG(LogAudio, Warning, TEXT("Cannot compute: application is playing"));
    return false;
  }

  // Make sure we are initialized.
  StartInternal(false);
  ApplyTransform();

  // Gather Geometries and Materials
  GatherGeometriesAndMaterials();

  // Collect all the file names to checkout in source control, both this Map and Geo files
  // Note this is done here because it must be done before attempting to write to file (perforce is read only until checked out)
  TArray<FString> FilePathsToCheckout;
  FString FullFilePath = FPaths::ProjectContentDir() / FilePath;
  FilePathsToCheckout.Add(FullFilePath);

  // Upload all geometries and materials
  Hash = FString(); // empty hash for this new computation
  TMap<FString, TArray<FString>> GeometryFileNames;
  const UMetaXRAcousticProjectSettings* Settings = GetDefault<UMetaXRAcousticProjectSettings>();
  for (UMetaXRAcousticGeometry* GeometryComponent : Geometries) {
    // Start up each geometry component to prepare for the map bake
    if (!GeometryComponent->StartInternal()) {
      DestroyInternal();
      // Don't leave any geometries we attempted to start hanging
      for (UMetaXRAcousticGeometry* Geo : Geometries) {
        Geo->DestroyInternal();
      }
      return false;
    }

    // Keep track of the number of geometries so we don't try to bake an empty scene
    Hash.Append(GeometryComponent->ComputeHash());

    // Keep track of which geometry files have been used so far
    FString GeometryFileName = GeometryComponent->GetFilePath();
    if (GeometryComponent->GetOwner()) {
      if (!GeometryFileNames.Contains(GeometryFileName)) {
        GeometryFileNames.Add(GeometryFileName);
      }
      GeometryFileNames[GeometryFileName].Add(GeometryComponent->GetOwner()->GetActorNameOrLabel());
    }

    // Record if this geometry needed to be checked out in source control
    if (GeometryComponent->IsFileEnabled() && Settings->bMapBakeWriteGeo) {
      FilePathsToCheckout.Add(FPaths::ProjectContentDir() / GeometryComponent->GetFilePath());
    }
  }

  for (UMetaXRAcousticMaterial* MaterialComponent : Materials) {
    // Hash materials (Note we don't need to StartInternal() for the material as that happens internal to geometry startup)
    MaterialComponent->AppendHash(Hash);
  }

  if (Geometries.Num() == 0) {
    UE_LOG(LogAudio, Warning, TEXT("Precompute failed: No geometry"));
    DestroyInternal();
    return false;
  }

  // Warn the user if they have multiple geometries that have the same file name as this could cause only one of them to load
  for (const TPair<FString, TArray<FString>>& GeometryNames : GeometryFileNames) {
    FString UniqueFileName = GeometryNames.Key;
    TArray<FString> ComponentsUsingName = GeometryNames.Value;
    if (ComponentsUsingName.Num() > 1) {
      UE_LOG(
          LogAudio,
          Warning,
          TEXT(
              "There are multiple geometry components with the file name %s. This could cause overwriting and therefore not loading some geometry"),
          *UniqueFileName);
      for (FString DuplicateGeometryComponent : ComponentsUsingName) {
        UE_LOG(LogAudio, Warning, TEXT("Component %s has a duplicate file name %s"), *DuplicateGeometryComponent, *UniqueFileName);
      }
    }
  }

  // Perform the source control checkout before the computation and writing of files
  MetaXRAudioUtilities::CheckOutFilesInSourceControl(FilePathsToCheckout);

  // Initialize the scene and start the job on the background thread.
  bComputing = true;
  bComputeCanceled = false;
  bComputeFinished = false;
  bComputeSucceeded = false;

  if (MappingTask) {
    bComputeFinished = true;
    bComputeCanceled = true;
    MappingTask->Cancel();
    MappingTask->EnsureCompletion();
    MappingTask.Reset();
    DestroyInternal();
    return false;
  }

  StartTimer();
  bComputeCanceled = false;
  MappingTask = MakeShareable(new FAsyncTask<FAsyncSceneMappingTask>(this, CachedMap, MapParameters));
  MappingTask->GetTask().bMapOnly = bMapOnly;
  MappingTask->StartBackgroundTask();

  // This prevents the engine from proceeding to the next step until the compute has finished on its thread
  // This is used for bulk baking where each bake must complete before opening the next level
  if (bBlockingCompute) {
    MappingTask->EnsureCompletion();
    FinishCompute();
  }

  return true;
}

/// Do final cleanup that can't be done on the async thread.
/**
 * This is called by the custom editor from the main thread
 * after this.computeFinished == true. Don't call it otherwise.
 */
void UMetaXRAcousticMap::FinishCompute() {
  if (MappingTask != nullptr) {
    // Wait until the compute thread is done.
    // Usually it is already finished by now, but in case of early termination (e.g. via OnDestroy()), we need to wait.
    MappingTask->EnsureCompletion();
  }

  // Setup the file paths for the output file.
#if WITH_EDITOR
  GenerateFileNameIfEmpty();
#endif
  FString FullFilePath = FPaths::ProjectContentDir() / FilePath;

  // Write IR to a file
  if (bComputeSucceeded && !bComputeCanceled) {
    if (OVRA_CALL(ovrAudio_AudioSceneIRWriteFile)(CachedMap, TCHAR_TO_ANSI(*FullFilePath)) != ovrSuccess) {
      UE_LOG(LogAudio, Warning, TEXT("Error writing Acoustic Map to file"));
    } else {
      UE_LOG(LogAudio, Display, TEXT("Acoustic Map finished generating to %s"), *FullFilePath);
    }
  }

  // Signal that the compute is finished.
  // This must be before the call to sceneIR.DestroyInternal() below to prevent stack overflow.
  bComputeFinished = true;
  bComputing = false;

  // Clean up scene objects.
  DestroyInternal();

  // Collect all the file names to checkout in source control, both this Map and Geo files
  TArray<FString> FilePathsToCheckout;
  FilePathsToCheckout.Add(FullFilePath);

  // Clean up geometry and materials. Write to file first if this setting is enabled
  const UMetaXRAcousticProjectSettings* Settings = GetDefault<UMetaXRAcousticProjectSettings>();
  for (UMetaXRAcousticGeometry* GeometryComponent : Geometries) {
    if (GeometryComponent->IsFileEnabled() && Settings->bMapBakeWriteGeo && !bComputeCanceled) {
      GeometryComponent->WriteFileInternal(GeometryComponent->GetHandle());
      FilePathsToCheckout.Add(FPaths::ProjectContentDir() / GeometryComponent->GetFilePath());
    }
    GeometryComponent->DestroyInternal();
  }

#if WITH_EDITOR
  MetaXRAudioUtilities::CheckOutFilesInSourceControl(FilePathsToCheckout);
#endif // WITH_EDITOR

  // Reset for next time.
  MappingTask.Reset();

  // This exists to fix an issue with point gizmos disapearing immediately after first bake.
  // After hitting 'Bake Acoustics' button in detail panel (FMetaXRAcousticMapDetails::CustomizeDetails) for first time
  // with no previous bake data...
  {
    AActor* AcousticMapActor = GetOwner();
    if (!AcousticMapActor)
      return;

    AcousticMapActor->UpdateComponentTransforms();
  }
}

// Gather all geometry and materials in the level in their respective lists
void UMetaXRAcousticMap::GatherGeometriesAndMaterials() {
  TArray<UMetaXRAcousticGeometry*> GeometryList;
  TArray<UMetaXRAcousticMaterial*> MaterialList;
  UWorld* World = GetWorld();
  const UMetaXRAcousticProjectSettings* Settings = GetDefault<UMetaXRAcousticProjectSettings>();
  for (TActorIterator<AActor> ActorItr(World); ActorItr; ++ActorItr) {
    AActor* CurrentActor = *ActorItr;
    UMetaXRAcousticGeometry* GeometryComponent = CurrentActor->FindComponentByClass<UMetaXRAcousticGeometry>();
    if (GeometryComponent) {
      GeometryList.Add(GeometryComponent);
    }

    UMetaXRAcousticMaterial* MaterialComponent = CurrentActor->FindComponentByClass<UMetaXRAcousticMaterial>();
    if (MaterialComponent) {
      MaterialList.Add(MaterialComponent);
    }
  }
  Geometries = GeometryList;
  Materials = MaterialList;
}

void UMetaXRAcousticMap::UpdateCachedPoints() {
  // Don't update the visualizer if the bake was cancelled
  if (bComputeCanceled) {
    return;
  }

  size_t NewPointCount;
  if (OVRA_CALL(ovrAudio_AudioSceneIRGetPointCount)(CachedMap, &NewPointCount) != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to get point count of map %p"), CachedMap);
  }

  TArray<float> Points;
  Points.SetNumUninitialized(NewPointCount * 3);
  if (OVRA_CALL(ovrAudio_AudioSceneIRGetPoints)(CachedMap, Points.GetData(), NewPointCount) != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to get points of map %p"), CachedMap);
  }

  ovrAudioSceneIRStatus NewStatus;
  if (OVRA_CALL(ovrAudio_AudioSceneIRGetStatus)(CachedMap, &NewStatus) != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to get status of map %p"), CachedMap);
  }
  Status = static_cast<EAcousticMapStatus>(NewStatus);

  // Keep map points stored in ovrAudio axis with no acoustic map transform applied
  SetPoints(Points, NewPointCount);

  IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
  FString FullFilePath = FPaths::ProjectContentDir() / FilePath;
  if (PlatformFile.FileExists(*FullFilePath)) {
    IFileHandle* FileHandle = PlatformFile.OpenRead(*FullFilePath);
    if (FileHandle) {
      DataSize = FileHandle->Size();
    }
    delete FileHandle;
  }
}
#endif

void UMetaXRAcousticMap::OnRegister() {
  Super::OnRegister();
#if WITH_EDITOR
  CheckIfOnlyMapInLevel();
  GenerateFileNameIfEmpty();
#endif
  CheckMapTransformValid();
  StartInternal();
  if (!MetaXRAudioUtilities::PlayModeActive(GetWorld())) {
    DestroyInternal();
  }
}

void UMetaXRAcousticMap::OnUnregister() {
  Super::OnUnregister();
  DestroyInternal();
}

void UMetaXRAcousticMap::BeginDestroy() {
  Super::BeginDestroy();

#if WITH_EDITOR
  if (MappingTask) {
    bComputeCanceled = true;
    MappingTask->Cancel();
    MappingTask->EnsureCompletion();
    MappingTask.Reset();
  }
#endif

  DestroyInternal();
}

void UMetaXRAcousticMap::ApplyTransform() {
  CheckMapTransformValid();
  FTransform UETransform = GetComponentTransform();
  float OVRTransform[16];
  MetaXRAudioUtilities::ConvertUETransformToOVRTransform(UETransform, OVRTransform);

#if WITH_EDITOR
  // Warn user in editor if the transform has any scaling (not allowed).
  FVector Scale = UETransform.GetScale3D();
  float Epsilon = 0.000001f;
  if (fabs(fabs(Scale.X) - 1.0f) > Epsilon || fabs(fabs(Scale.Y) - 1.0f) > Epsilon || fabs(fabs(Scale.Z) - 1.0f) > Epsilon) {
    UE_LOG(
        LogAudio,
        Error,
        TEXT("Acoustic Map object transform cannot have any scaling. This may result in incorrect audio.\nCurrent scale = {%f, %f, %f}"),
        Scale.X,
        Scale.Y,
        Scale.Z);
  }
#endif

  if (OVRA_CALL(ovrAudio_AudioSceneIRSetTransform)(CachedMap, OVRTransform) != ovrSuccess) {
    UE_LOG(LogAudio, Log, TEXT("Failed to set transform for Acoustic Map %p"), CachedMap);
  } else {
    UE_LOG(LogAudio, Log, TEXT("Set transform for Acoustic Map %p"), CachedMap);
  }

#if WITH_EDITOR
  RefreshSphereGizmo();
#endif

  PreviousTransform = UETransform;
}

// We do not allow UMapComponent transformations as we want our Map to stay in sync with expectations
void UMetaXRAcousticMap::CheckMapTransformValid() {
  if (GetOwner() == nullptr) {
    return;
  }
  if (!GetOwner()->GetTransform().Equals(GetComponentTransform())) {
    ResetRelativeTransform();
    UE_LOG(
        LogAudio,
        Warning,
        TEXT(
            "You cannot change the transform of the UMapComponent, only the transform of its attched Aactor. This ensures the audio map stays in sync with the physical geometry."));
  }
}

#if WITH_EDITOR
/// Signal to the precomputation thread that it should stop computing the IR
void UMetaXRAcousticMap::CancelCompute() {
  bComputeCanceled = true;
}
#endif

FPrimitiveSceneProxy* UMetaXRAcousticMap::CreateSceneProxy() {
#if WITH_EDITOR_GIZMOS
  return new FMetaXRAcousticMapSceneProxy(this);
#else
  return nullptr;
#endif
}

#if WITH_EDITOR
// This function tells the renderer where the Map Points are so it can only render it while in frame
FBoxSphereBounds UMetaXRAcousticMap::CalcBounds(const FTransform& LocalToWorld) const {
  // This constructor will compute a bounding box based on our points
  if (GetNumPoints() == 0) {
    FBoxSphereBounds EmptyBounds;
    return EmptyBounds;
  }
  TArray<FVector> PointsUE = GetPointsUE();
  FBoxSphereBounds MapBounds(&PointsUE[0], PointsUE.Num());
  return MapBounds;
}
#endif

void UMetaXRAcousticMap::TickComponent(float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) {
  Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

#if WITH_EDITOR
  if (bComputing) {
    // Try to get rid of the thread if the user cancelled
    if (bComputeCanceled && !MappingTask->IsDone()) {
      MappingTask->TryAbandonTask();
    }

    // Poll to see if the async compute was finished.
    if (MappingTask->IsDone() || bComputeFinished) {
      bool wasCancelled = bComputeCanceled;

      // Do final cleanup on the main thread after computing the IR.
      FinishCompute();

      if (wasCancelled) {
        UE_LOG(LogAudio, Warning, TEXT("Attempting to load previous bake %s"), *FilePath);
        DestroyInternal();
        StartInternal();
      }
    }
  }
#endif

  FTransform Transform = GetComponentTransform();
  if (!Transform.Equals(PreviousTransform)) {
    ApplyTransform();
  }
}

#if WITH_EDITOR
void UMetaXRAcousticMap::PostEditChangeProperty(struct FPropertyChangedEvent& PropertyChangedEvent) {
  CheckMapTransformValid();
  // Must be called after our updated above in order to make sure everythings updated correctly.
  Super::PostEditChangeProperty(PropertyChangedEvent);
}

void UMetaXRAcousticMap::PostEditComponentMove(bool bFinished) {
  ApplyTransform();
}

void UMetaXRAcousticMap::Activate(bool bReset) {
  if (CachedMap == nullptr) {
    return;
  }

  ovrResult Result;
  Result = OVRA_CALL(ovrAudio_AudioSceneIRSetEnabled)(CachedMap, true);
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to Set Acoustic Map %p to enabled"), CachedMap);
  } else {
    UE_LOG(LogAudio, Log, TEXT("Set Acoustic Map %p to enabled"), CachedMap);
  }
}

void UMetaXRAcousticMap::Deactivate() {
  ovrResult Result;
  Result = OVRA_CALL(ovrAudio_AudioSceneIRSetEnabled)(CachedMap, false);
  if (Result != ovrSuccess) {
    UE_LOG(LogAudio, Warning, TEXT("Failed to Set Acoustic Map %p to disabled"), CachedMap);
  } else {
    UE_LOG(LogAudio, Log, TEXT("Set Acoustic Map %p to disabed"), CachedMap);
  }
}

FVector UMetaXRAcousticMap::GetNewPointForRay(FVector RayOrigin, FVector RayDirection) {
  float DefaultDistance = 400.0f; // How far away to place a point if the ray hits nothing
  float TraceDistance = 60000.0f; // How far away to fire the ray trace before giving up
  FVector EndPosition = RayOrigin + (RayDirection * TraceDistance); // The point at the end of our longest possible ray

  // Try to perform raytracing to find a point in front of the camera that is not blocked by geometry.
  FVector NewPointPosition;
  UWorld* World = GetWorld();
  if (World != nullptr) {
    // Setup variables for unreal's raytracing function
    FHitResult HitResult;
    FCollisionObjectQueryParams ObjectTypes;
    ObjectTypes.AddObjectTypesToQuery(ECC_WorldStatic);
    ObjectTypes.AddObjectTypesToQuery(ECC_WorldDynamic);
    FCollisionQueryParams QueryParams;

    // Perform a single raytrace which will tell us the first blocking hit.
    bool HitFound = World->LineTraceSingleByObjectType(HitResult, RayOrigin, EndPosition, ObjectTypes, QueryParams);
    if (HitResult.bBlockingHit && IsValid(HitResult.GetActor())) {
      // Place the point slightly away from the hit point to avoid placing points on walls.
      float bias = 300.0f;
      NewPointPosition = RayOrigin + (RayDirection * FMath::Max(HitResult.Distance - bias, 0.0f));

      if (bNoFloating == false) {
        return NewPointPosition;
      }

      // Trace two rays down and up to place the point at the right height.
      FVector DownRayEndPosition = NewPointPosition + (GravityVector.GetUnsafeNormal() * TraceDistance);
      if (World->LineTraceSingleByObjectType(HitResult, NewPointPosition, DownRayEndPosition, ObjectTypes, QueryParams)) {
        float downDistance = HitResult.Distance;
        float targetHeight = NewPointPosition.Z;

        if (downDistance > MaxHeight) {
          targetHeight = HeadHeight;
        } else if (downDistance < HeadHeight) {
          FVector UpRayEndPosition = NewPointPosition - (GravityVector.GetUnsafeNormal() * TraceDistance);
          if (World->LineTraceSingleByObjectType(HitResult, NewPointPosition, UpRayEndPosition, ObjectTypes, QueryParams)) {
            // Move point so that it is either at head height or is at the floor/ceiling midpoint if that is less.
            float midHeight = 0.5f * (downDistance + HitResult.Distance);
            targetHeight = FMath::Min(HeadHeight, midHeight);
          }
        }

        // height adjustment
        NewPointPosition += GravityVector * (downDistance - targetHeight);
      }
      return NewPointPosition;
    } else {
      // Facing empty space, place the point slightly in front of the camera.
      return RayOrigin + (RayDirection * DefaultDistance);
    }
  }

  // Place slightly in front of camera as fallback if cannot raytrace or we didn't hit anything
  return RayOrigin + (RayDirection * DefaultDistance);
}

void UMetaXRAcousticMap::SetupSphereVertices() {
  if (!SphereVertices.IsEmpty() && !SphereIndices.IsEmpty()) {
    return;
  }

  for (uint32_t Stack = 0; Stack <= META_XR_AUDIO_MAP_SPHERE_NUM_STACKS; ++Stack) {
    for (uint32_t Slice = 0; Slice <= META_XR_AUDIO_MAP_SPHERE_NUM_SLICES; ++Slice) {
      const float XSegment = static_cast<float>(Slice) / static_cast<float>(META_XR_AUDIO_MAP_SPHERE_NUM_SLICES);
      const float YSegment = static_cast<float>(Stack) / static_cast<float>(META_XR_AUDIO_MAP_SPHERE_NUM_STACKS);
      const float XPos = FMath::Cos(XSegment * 2 * PI) * FMath::Sin(YSegment * PI);
      const float YPos = FMath::Cos(YSegment * PI);
      const float ZPos = FMath::Sin(XSegment * 2 * PI) * FMath::Sin(YSegment * PI);
      SphereVertices.Add(FVector(XPos, YPos, ZPos));
    }
  }

  for (uint32_t Stack = 0; Stack < META_XR_AUDIO_MAP_SPHERE_NUM_STACKS; ++Stack) {
    for (uint32_t Slice = 0; Slice < META_XR_AUDIO_MAP_SPHERE_NUM_SLICES; ++Slice) {
      SphereIndices.Add((Stack + 1) * (META_XR_AUDIO_MAP_SPHERE_NUM_SLICES + 1) + Slice);
      SphereIndices.Add(Stack * (META_XR_AUDIO_MAP_SPHERE_NUM_SLICES + 1) + Slice);
      SphereIndices.Add(Stack * (META_XR_AUDIO_MAP_SPHERE_NUM_SLICES + 1) + Slice + 1);

      SphereIndices.Add((Stack + 1) * (META_XR_AUDIO_MAP_SPHERE_NUM_SLICES + 1) + Slice);
      SphereIndices.Add(Stack * (META_XR_AUDIO_MAP_SPHERE_NUM_SLICES + 1) + Slice + 1);
      SphereIndices.Add((Stack + 1) * (META_XR_AUDIO_MAP_SPHERE_NUM_SLICES + 1) + Slice + 1);
    }
  }
}

int UMetaXRAcousticMap::GetNumPoints() const {
  return PointsOVR.Num();
}

void UMetaXRAcousticMap::AddPoint(FVector PointUE) {
  PointsOVR.Add(MetaXRAudioUtilities::ToOVRVector(GetComponentTransform().Inverse().TransformPosition(PointUE)));
  RefreshSphereGizmo();
}

void UMetaXRAcousticMap::RemovePoint(int SelectedPoint) {
  PointsOVR.RemoveAt(SelectedPoint);
  RefreshSphereGizmo();
}

void UMetaXRAcousticMap::RemoveSelectedPoint() {
  PointsOVR.RemoveAt(SelectedPointIndex);
  ResetSelectedPoint();
  RefreshSphereGizmo();
}

void UMetaXRAcousticMap::MoveSelectedPoint(FVector NewLocationUE) {
  if (!PointIsSelected())
    return;
  PointsOVR[SelectedPointIndex] = MetaXRAudioUtilities::ToOVRVector(GetComponentTransform().Inverse().TransformPosition(NewLocationUE));
  RefreshSphereGizmo();
}

void UMetaXRAcousticMap::SetPoints(TArray<float> NewPointsOVR, int NumPoints) {
  PointsOVR.SetNumUninitialized(NumPoints);
  for (int32 i = 0; i < NumPoints; i++) {
    FVector Point;
    Point.X = NewPointsOVR[i * 3];
    Point.Y = NewPointsOVR[i * 3 + 1];
    Point.Z = NewPointsOVR[i * 3 + 2];
    PointsOVR[i] = Point;
  }
  RefreshSphereGizmo();
}

FVector UMetaXRAcousticMap::GetPointUE(int SelectedPoint) const {
  return GetComponentTransform().TransformPosition(MetaXRAudioUtilities::ToUEVector(PointsOVR[SelectedPoint]));
}

TArray<FVector> UMetaXRAcousticMap::GetPointsUE() const {
  TArray<FVector> ReturnArray;
  for (int i = 0; i < PointsOVR.Num(); i++) {
    ReturnArray.Add(GetPointUE(i));
  }
  return ReturnArray;
}

FVector UMetaXRAcousticMap::GetSelectedPointUE() const {
  return GetPointUE(SelectedPointIndex);
}

void UMetaXRAcousticMap::SetSelectedPoint(int SelectedPoint) {
  SelectedPointIndex = SelectedPoint;
  RefreshSphereGizmo();
}

void UMetaXRAcousticMap::ResetSelectedPoint() {
  SetSelectedPoint(MAX_int32);
}

bool UMetaXRAcousticMap::PointIsSelected() const {
  return (SelectedPointIndex < PointsOVR.Num() && SelectedPointIndex >= 0);
}

bool UMetaXRAcousticMap::HasPoints() const {
  return !PointsOVR.IsEmpty();
}

void UMetaXRAcousticMap::RefreshSphereGizmo() {
  FDynamicMeshVertex Vertex;
  GizmoSelectedIndices.Empty();
  GizmoVertices.Empty();
  GizmoIndices.Empty();
  for (int i = 0; i < GetNumPoints(); i++) {
    FTransform SphereTransform(FQuat::Identity, GetPointUE(i), FVector(META_XR_AUDIO_MAP_SPHERE_RADIUS));
    for (const FVector& Vert : SphereVertices) {
      Vertex.Position = MetaXRAudioUtilities::VectorToVector3f(SphereTransform.TransformPosition(Vert));
      GizmoVertices.Add(Vertex);
    }
    int IndexOffset = SphereVertices.Num() * i;
    for (const uint32& Index : SphereIndices) {
      // Save the selected point to separate array to render as a different color
      if (i == SelectedPointIndex) {
        GizmoSelectedIndices.Add(Index + IndexOffset);
      } // Save the unselected points to the same array to maximize render speed
      else {
        GizmoIndices.Add(Index + IndexOffset);
      }
    }
  }
}

FMetaXRAcousticMapSceneProxy::FMetaXRAcousticMapSceneProxy(const UPrimitiveComponent* InComponent) : FDebugRenderSceneProxy(InComponent) {
  AcousticMapComponent = Cast<UMetaXRAcousticMap>(InComponent);
}

FPrimitiveViewRelevance FMetaXRAcousticMapSceneProxy::GetViewRelevance(const FSceneView* View) const {
  static const IConsoleVariable* const MetaXRAudioGlobalGizmoCVAR = IConsoleManager::Get().FindConsoleVariable(TEXT("MetaXRAudioGizmos"));
  static const IConsoleVariable* const MetaXRAudioMapGizmoCVAR = IConsoleManager::Get().FindConsoleVariable(TEXT("MetaXRAudioGizmos.Maps"));
  bool bVisible = MetaXRAudioMapGizmoCVAR && MetaXRAudioMapGizmoCVAR->GetInt() != 0 && MetaXRAudioGlobalGizmoCVAR &&
      MetaXRAudioGlobalGizmoCVAR->GetInt() != 0;
  FPrimitiveViewRelevance Result;
  Result.bDrawRelevance = bVisible;
  Result.bDynamicRelevance = true;
  return Result;
}

void FMetaXRAcousticMapSceneProxy::GetDynamicMeshElements(
    const TArray<const FSceneView*>& Views,
    const FSceneViewFamily& ViewFamily,
    uint32 VisibilityMap,
    FMeshElementCollector& Collector) const {
  FColoredMaterialRenderProxy* RedMaterial =
      new FColoredMaterialRenderProxy(GEngine->LevelColorationUnlitMaterial->GetRenderProxy(), FLinearColor::Red);
  FColoredMaterialRenderProxy* YellowMaterial =
      new FColoredMaterialRenderProxy(GEngine->LevelColorationUnlitMaterial->GetRenderProxy(), FLinearColor::Yellow);
  Collector.RegisterOneFrameMaterialProxy(RedMaterial);
  Collector.RegisterOneFrameMaterialProxy(YellowMaterial);

  for (int32 ViewIndex = 0; ViewIndex < Views.Num(); ViewIndex++) {
    if (VisibilityMap & (1 << ViewIndex)) {
      const FSceneView* View = Views[ViewIndex];
      if (!AcousticMapComponent->GizmoVertices.IsEmpty() && !AcousticMapComponent->GizmoIndices.IsEmpty()) {
        // Draw all the points in yellow
        FDynamicMeshBuilder MeshBuilder(View->GetFeatureLevel());
        MeshBuilder.AddVertices(AcousticMapComponent->GizmoVertices);
        MeshBuilder.AddTriangles(AcousticMapComponent->GizmoIndices);
        MeshBuilder.GetMesh(
            FMatrix::Identity, // The transforms are applied during RefreshSphereGizmo()
            YellowMaterial,
            SDPG_World,
            true,
            false,
            false,
            ViewIndex,
            Collector);
      }

      // If there is a selected point, draw it in red
      if (!AcousticMapComponent->GizmoVertices.IsEmpty() && !AcousticMapComponent->GizmoSelectedIndices.IsEmpty()) {
        FDynamicMeshBuilder SelectedMeshBuilder(View->GetFeatureLevel());
        SelectedMeshBuilder.AddVertices(AcousticMapComponent->GizmoVertices);
        SelectedMeshBuilder.AddTriangles(AcousticMapComponent->GizmoSelectedIndices);
        SelectedMeshBuilder.GetMesh(
            FMatrix::Identity, // The transforms are applied during RefreshSphereGizmo()
            RedMaterial,
            SDPG_World,
            true,
            false,
            false,
            ViewIndex,
            Collector);
      }
    }
  }
}
#endif // WITH_EDITOR
